"""Add present_stocks to menu_items

Revision ID: db9d43dd9339
Revises: 4f206af702e0
Create Date: 2026-02-04 21:53:32.195449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'db9d43dd9339'
down_revision: Union[str, None] = '4f206af702e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_actuals')
    op.drop_table('revenue_forecasts')
    op.drop_index('idx_menu_items_category', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_table('customer_behavior_patterns')
    op.drop_table('inventory_logs')
    op.drop_table('churn_predictions')
    op.drop_table('predictive_models')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ai_recommendations_id', table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index('ix_user_interactions_id', table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_table('billing_settings')
    op.drop_index('ix_payments_payment_reference', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_revenue_summary_date', table_name='revenue_summary')
    op.drop_table('revenue_summary')
    op.drop_index('idx_order_items_menu_item', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_demand_forecasts_date_period', table_name='demand_forecasts')
    op.drop_index('idx_demand_forecasts_menu_item', table_name='demand_forecasts')
    op.drop_table('demand_forecasts')
    op.drop_index('idx_orders_status_created', table_name='orders')
    op.drop_table('orders')
    op.drop_table('queue_forecasts')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_inventory_menu_item', table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('peak_hour_predictions')
    op.drop_table('preparation_time_predictions')
    op.drop_index('ix_user_preferences_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('preference_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('preference_value', sa.VARCHAR(length=100), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_preferences_id', 'user_preferences', ['id'], unique=False)
    op.create_table('preparation_time_predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('predicted_time', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('factors', sqlite.JSON(), nullable=True),
    sa.Column('actual_time', sa.INTEGER(), nullable=True),
    sa.Column('prediction_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peak_hour_predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prediction_date', sa.DATETIME(), nullable=False),
    sa.Column('peak_start_time', sa.DATETIME(), nullable=False),
    sa.Column('peak_end_time', sa.DATETIME(), nullable=False),
    sa.Column('predicted_orders', sa.INTEGER(), nullable=False),
    sa.Column('recommended_staff', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('factors', sqlite.JSON(), nullable=True),
    sa.Column('actual_orders', sa.INTEGER(), nullable=True),
    sa.Column('actual_staff_needed', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id')
    )
    op.create_index('idx_inventory_menu_item', 'inventory', ['menu_item_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=False),
    sa.Column('tax_amount', sa.FLOAT(), nullable=False),
    sa.Column('discount_amount', sa.FLOAT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('paid_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=1)
    op.create_table('queue_forecasts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('predicted_time', sa.DATETIME(), nullable=False),
    sa.Column('predicted_queue_length', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('factors', sqlite.JSON(), nullable=True),
    sa.Column('actual_queue_length', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('queue_position', sa.INTEGER(), nullable=True),
    sa.Column('predicted_wait_time', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('started_preparation_at', sa.DATETIME(), nullable=True),
    sa.Column('ready_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('total_amount', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('demand_forecasts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('forecast_date', sa.DATETIME(), nullable=False),
    sa.Column('predicted_quantity', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('forecast_period', sa.VARCHAR(), nullable=False),
    sa.Column('factors', sqlite.JSON(), nullable=True),
    sa.Column('actual_quantity', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demand_forecasts_menu_item', 'demand_forecasts', ['menu_item_id'], unique=False)
    op.create_index('idx_demand_forecasts_date_period', 'demand_forecasts', ['forecast_date', 'forecast_period'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_menu_item', 'order_items', ['menu_item_id'], unique=False)
    op.create_table('revenue_summary',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('total_revenue', sa.FLOAT(), nullable=False),
    sa.Column('total_orders', sa.INTEGER(), nullable=False),
    sa.Column('total_invoices', sa.INTEGER(), nullable=False),
    sa.Column('paid_invoices', sa.INTEGER(), nullable=False),
    sa.Column('pending_invoices', sa.INTEGER(), nullable=False),
    sa.Column('cash_revenue', sa.FLOAT(), nullable=False),
    sa.Column('card_revenue', sa.FLOAT(), nullable=False),
    sa.Column('upi_revenue', sa.FLOAT(), nullable=False),
    sa.Column('other_revenue', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revenue_summary_date', 'revenue_summary', ['date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gateway_response', sa.TEXT(), nullable=True),
    sa.Column('gateway_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_payment_reference', 'payments', ['payment_reference'], unique=1)
    op.create_table('billing_settings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tax_rate', sa.FLOAT(), nullable=False),
    sa.Column('tax_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('currency_symbol', sa.VARCHAR(length=5), nullable=False),
    sa.Column('invoice_prefix', sa.VARCHAR(length=20), nullable=False),
    sa.Column('invoice_number_length', sa.INTEGER(), nullable=False),
    sa.Column('accepted_payment_methods', sa.TEXT(), nullable=True),
    sa.Column('auto_mark_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('payment_due_days', sa.INTEGER(), nullable=False),
    sa.Column('reminder_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('business_address', sa.TEXT(), nullable=True),
    sa.Column('business_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('business_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gst_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('interaction_value', sa.FLOAT(), nullable=True),
    sa.Column('context_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_interactions_id', 'user_interactions', ['id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('recommendation_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_recommendations_id', 'ai_recommendations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('predictive_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('model_version', sa.VARCHAR(), nullable=False),
    sa.Column('model_type', sa.VARCHAR(), nullable=False),
    sa.Column('accuracy_score', sa.FLOAT(), nullable=True),
    sa.Column('last_trained', sa.DATETIME(), nullable=True),
    sa.Column('training_data_size', sa.INTEGER(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('churn_predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('churn_probability', sa.FLOAT(), nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), nullable=False),
    sa.Column('risk_factors', sqlite.JSON(), nullable=True),
    sa.Column('recommended_action', sa.TEXT(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('prediction_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_churn', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity_used', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_behavior_patterns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(), nullable=False),
    sa.Column('pattern_data', sqlite.JSON(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('base_prep_time', sa.INTEGER(), nullable=True),
    sa.Column('calories', sa.INTEGER(), nullable=True),
    sa.Column('is_vegetarian', sa.BOOLEAN(), nullable=True),
    sa.Column('is_spicy', sa.BOOLEAN(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_items_category', 'menu_items', ['category'], unique=False)
    op.create_table('revenue_forecasts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('forecast_date', sa.DATETIME(), nullable=False),
    sa.Column('forecast_period', sa.VARCHAR(), nullable=False),
    sa.Column('predicted_revenue', sa.FLOAT(), nullable=False),
    sa.Column('predicted_orders', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('factors', sqlite.JSON(), nullable=True),
    sa.Column('actual_revenue', sa.FLOAT(), nullable=True),
    sa.Column('actual_orders', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_actuals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('queue_length', sa.INTEGER(), nullable=False),
    sa.Column('wait_time', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('forecast_id', sa.INTEGER(), nullable=True),
    sa.Column('factors', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['queue_forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
